export const metadata = {
  title: 'Receitas',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  console.log("montando layout") //Receita 2a
  return (
    <html lang="en">
      <body>
        <nav>
          <div>Menu principal</div> 
        </nav>
        {children}
      </body>
    </html>
  )
}
