import "./styles/globals.css";
export const metadata = {
  title: 'Receitas',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  console.log("montando layout") //Receita 2a
  return (
    <html lang="en">
      <body>
        <nav>
          <div className="bg-red-700 text-white p-6 rounded-lg shadow-lg flex justify-center">
            <div className="text-xl font-bold">Menu Principal</div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
